FROM node:10-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# Install dependencies
COPY package.json .
#RUN apk add g++ make python nodejs
RUN npm install       # Install required NPM modules
#RUN npm i hedgehog-client
#RUN npm install -g grunt-cli
#RUN npm install grunt-docker --save-dev
#RUN cd /usr/src/app
#RUN grunt protoc      # Generate Protobuf Javascript files
#RUN grunt build       # compile TypeScript sources
RUN npm install -g socket.io
RUN npm install
RUN sh -c "ls ./node_modules"
RUN npm install -g nodemon
# Bundle app source
COPY . .
# Exports
EXPOSE 8080
CMD [ "npm", "run", "start.dev" ]
